/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRunsRouteImport } from './routes/_authenticated/ai-runs'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedSettingsRunnerRouteImport } from './routes/_authenticated/settings/runner'
import { Route as AuthenticatedSettingsPromptTemplatesRouteImport } from './routes/_authenticated/settings/prompt-templates'
import { Route as AuthenticatedSettingsMcpServersRouteImport } from './routes/_authenticated/settings/mcp-servers'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedSettingsMcpServersMcpConnectTestRouteImport } from './routes/_authenticated/settings/mcp-servers/mcp-connect-test'
import { Route as AuthenticatedSettingsMcpServersCreateRouteImport } from './routes/_authenticated/settings/mcp-servers/create'
import { Route as AuthenticatedProjectsProjectIdWorkflowsRouteImport } from './routes/_authenticated/projects/$projectId/workflows'
import { Route as AuthenticatedProjectsProjectIdTechSpecsRouteImport } from './routes/_authenticated/projects/$projectId/tech-specs'
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated/projects/$projectId/tasks'
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/projects/$projectId/settings'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects/$projectId/members'
import { Route as AuthenticatedProjectsProjectIdMasterScheduleRouteImport } from './routes/_authenticated/projects/$projectId/master-schedule'
import { Route as AuthenticatedProjectsProjectIdCodingPlanRouteImport } from './routes/_authenticated/projects/$projectId/coding-plan'
import { Route as AuthenticatedProjectsProjectIdBusinessLogicRouteImport } from './routes/_authenticated/projects/$projectId/business-logic'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRunsRoute = AuthenticatedAiRunsRouteImport.update({
  id: '/ai-runs',
  path: '/ai-runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRunnerRoute =
  AuthenticatedSettingsRunnerRouteImport.update({
    id: '/settings/runner',
    path: '/settings/runner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPromptTemplatesRoute =
  AuthenticatedSettingsPromptTemplatesRouteImport.update({
    id: '/settings/prompt-templates',
    path: '/settings/prompt-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMcpServersRoute =
  AuthenticatedSettingsMcpServersRouteImport.update({
    id: '/settings/mcp-servers',
    path: '/settings/mcp-servers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMcpServersMcpConnectTestRoute =
  AuthenticatedSettingsMcpServersMcpConnectTestRouteImport.update({
    id: '/mcp-connect-test',
    path: '/mcp-connect-test',
    getParentRoute: () => AuthenticatedSettingsMcpServersRoute,
  } as any)
const AuthenticatedSettingsMcpServersCreateRoute =
  AuthenticatedSettingsMcpServersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSettingsMcpServersRoute,
  } as any)
const AuthenticatedProjectsProjectIdWorkflowsRoute =
  AuthenticatedProjectsProjectIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTechSpecsRoute =
  AuthenticatedProjectsProjectIdTechSpecsRouteImport.update({
    id: '/tech-specs',
    path: '/tech-specs',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMasterScheduleRoute =
  AuthenticatedProjectsProjectIdMasterScheduleRouteImport.update({
    id: '/master-schedule',
    path: '/master-schedule',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdCodingPlanRoute =
  AuthenticatedProjectsProjectIdCodingPlanRouteImport.update({
    id: '/coding-plan',
    path: '/coding-plan',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdBusinessLogicRoute =
  AuthenticatedProjectsProjectIdBusinessLogicRouteImport.update({
    id: '/business-logic',
    path: '/business-logic',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-runs': typeof AuthenticatedAiRunsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/mcp-servers': typeof AuthenticatedSettingsMcpServersRouteWithChildren
  '/settings/prompt-templates': typeof AuthenticatedSettingsPromptTemplatesRoute
  '/settings/runner': typeof AuthenticatedSettingsRunnerRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/business-logic': typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  '/projects/$projectId/coding-plan': typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  '/projects/$projectId/master-schedule': typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/tech-specs': typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  '/projects/$projectId/workflows': typeof AuthenticatedProjectsProjectIdWorkflowsRoute
  '/settings/mcp-servers/create': typeof AuthenticatedSettingsMcpServersCreateRoute
  '/settings/mcp-servers/mcp-connect-test': typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-runs': typeof AuthenticatedAiRunsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/mcp-servers': typeof AuthenticatedSettingsMcpServersRouteWithChildren
  '/settings/prompt-templates': typeof AuthenticatedSettingsPromptTemplatesRoute
  '/settings/runner': typeof AuthenticatedSettingsRunnerRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/business-logic': typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  '/projects/$projectId/coding-plan': typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  '/projects/$projectId/master-schedule': typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/tech-specs': typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  '/projects/$projectId/workflows': typeof AuthenticatedProjectsProjectIdWorkflowsRoute
  '/settings/mcp-servers/create': typeof AuthenticatedSettingsMcpServersCreateRoute
  '/settings/mcp-servers/mcp-connect-test': typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ai-runs': typeof AuthenticatedAiRunsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/mcp-servers': typeof AuthenticatedSettingsMcpServersRouteWithChildren
  '/_authenticated/settings/prompt-templates': typeof AuthenticatedSettingsPromptTemplatesRoute
  '/_authenticated/settings/runner': typeof AuthenticatedSettingsRunnerRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/business-logic': typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  '/_authenticated/projects/$projectId/coding-plan': typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  '/_authenticated/projects/$projectId/master-schedule': typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/_authenticated/projects/$projectId/tech-specs': typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  '/_authenticated/projects/$projectId/workflows': typeof AuthenticatedProjectsProjectIdWorkflowsRoute
  '/_authenticated/settings/mcp-servers/create': typeof AuthenticatedSettingsMcpServersCreateRoute
  '/_authenticated/settings/mcp-servers/mcp-connect-test': typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-runs'
    | '/dashboard'
    | '/teams'
    | '/projects/$projectId'
    | '/projects/create'
    | '/settings/integrations'
    | '/settings/mcp-servers'
    | '/settings/prompt-templates'
    | '/settings/runner'
    | '/projects/'
    | '/projects/$projectId/business-logic'
    | '/projects/$projectId/coding-plan'
    | '/projects/$projectId/master-schedule'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tech-specs'
    | '/projects/$projectId/workflows'
    | '/settings/mcp-servers/create'
    | '/settings/mcp-servers/mcp-connect-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-runs'
    | '/dashboard'
    | '/teams'
    | '/projects/$projectId'
    | '/projects/create'
    | '/settings/integrations'
    | '/settings/mcp-servers'
    | '/settings/prompt-templates'
    | '/settings/runner'
    | '/projects'
    | '/projects/$projectId/business-logic'
    | '/projects/$projectId/coding-plan'
    | '/projects/$projectId/master-schedule'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tech-specs'
    | '/projects/$projectId/workflows'
    | '/settings/mcp-servers/create'
    | '/settings/mcp-servers/mcp-connect-test'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ai-runs'
    | '/_authenticated/dashboard'
    | '/_authenticated/teams'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/create'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/mcp-servers'
    | '/_authenticated/settings/prompt-templates'
    | '/_authenticated/settings/runner'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/business-logic'
    | '/_authenticated/projects/$projectId/coding-plan'
    | '/_authenticated/projects/$projectId/master-schedule'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/projects/$projectId/tech-specs'
    | '/_authenticated/projects/$projectId/workflows'
    | '/_authenticated/settings/mcp-servers/create'
    | '/_authenticated/settings/mcp-servers/mcp-connect-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-runs': {
      id: '/_authenticated/ai-runs'
      path: '/ai-runs'
      fullPath: '/ai-runs'
      preLoaderRoute: typeof AuthenticatedAiRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/runner': {
      id: '/_authenticated/settings/runner'
      path: '/settings/runner'
      fullPath: '/settings/runner'
      preLoaderRoute: typeof AuthenticatedSettingsRunnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/prompt-templates': {
      id: '/_authenticated/settings/prompt-templates'
      path: '/settings/prompt-templates'
      fullPath: '/settings/prompt-templates'
      preLoaderRoute: typeof AuthenticatedSettingsPromptTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mcp-servers': {
      id: '/_authenticated/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mcp-servers/mcp-connect-test': {
      id: '/_authenticated/settings/mcp-servers/mcp-connect-test'
      path: '/mcp-connect-test'
      fullPath: '/settings/mcp-servers/mcp-connect-test'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersMcpConnectTestRouteImport
      parentRoute: typeof AuthenticatedSettingsMcpServersRoute
    }
    '/_authenticated/settings/mcp-servers/create': {
      id: '/_authenticated/settings/mcp-servers/create'
      path: '/create'
      fullPath: '/settings/mcp-servers/create'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersCreateRouteImport
      parentRoute: typeof AuthenticatedSettingsMcpServersRoute
    }
    '/_authenticated/projects/$projectId/workflows': {
      id: '/_authenticated/projects/$projectId/workflows'
      path: '/workflows'
      fullPath: '/projects/$projectId/workflows'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWorkflowsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tech-specs': {
      id: '/_authenticated/projects/$projectId/tech-specs'
      path: '/tech-specs'
      fullPath: '/projects/$projectId/tech-specs'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTechSpecsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/master-schedule': {
      id: '/_authenticated/projects/$projectId/master-schedule'
      path: '/master-schedule'
      fullPath: '/projects/$projectId/master-schedule'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMasterScheduleRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/coding-plan': {
      id: '/_authenticated/projects/$projectId/coding-plan'
      path: '/coding-plan'
      fullPath: '/projects/$projectId/coding-plan'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCodingPlanRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/business-logic': {
      id: '/_authenticated/projects/$projectId/business-logic'
      path: '/business-logic'
      fullPath: '/projects/$projectId/business-logic'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBusinessLogicRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdBusinessLogicRoute: typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  AuthenticatedProjectsProjectIdCodingPlanRoute: typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  AuthenticatedProjectsProjectIdMasterScheduleRoute: typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRoute
  AuthenticatedProjectsProjectIdTechSpecsRoute: typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  AuthenticatedProjectsProjectIdWorkflowsRoute: typeof AuthenticatedProjectsProjectIdWorkflowsRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdBusinessLogicRoute:
      AuthenticatedProjectsProjectIdBusinessLogicRoute,
    AuthenticatedProjectsProjectIdCodingPlanRoute:
      AuthenticatedProjectsProjectIdCodingPlanRoute,
    AuthenticatedProjectsProjectIdMasterScheduleRoute:
      AuthenticatedProjectsProjectIdMasterScheduleRoute,
    AuthenticatedProjectsProjectIdMembersRoute:
      AuthenticatedProjectsProjectIdMembersRoute,
    AuthenticatedProjectsProjectIdSettingsRoute:
      AuthenticatedProjectsProjectIdSettingsRoute,
    AuthenticatedProjectsProjectIdTasksRoute:
      AuthenticatedProjectsProjectIdTasksRoute,
    AuthenticatedProjectsProjectIdTechSpecsRoute:
      AuthenticatedProjectsProjectIdTechSpecsRoute,
    AuthenticatedProjectsProjectIdWorkflowsRoute:
      AuthenticatedProjectsProjectIdWorkflowsRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedSettingsMcpServersRouteChildren {
  AuthenticatedSettingsMcpServersCreateRoute: typeof AuthenticatedSettingsMcpServersCreateRoute
  AuthenticatedSettingsMcpServersMcpConnectTestRoute: typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
}

const AuthenticatedSettingsMcpServersRouteChildren: AuthenticatedSettingsMcpServersRouteChildren =
  {
    AuthenticatedSettingsMcpServersCreateRoute:
      AuthenticatedSettingsMcpServersCreateRoute,
    AuthenticatedSettingsMcpServersMcpConnectTestRoute:
      AuthenticatedSettingsMcpServersMcpConnectTestRoute,
  }

const AuthenticatedSettingsMcpServersRouteWithChildren =
  AuthenticatedSettingsMcpServersRoute._addFileChildren(
    AuthenticatedSettingsMcpServersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiRunsRoute: typeof AuthenticatedAiRunsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsMcpServersRoute: typeof AuthenticatedSettingsMcpServersRouteWithChildren
  AuthenticatedSettingsPromptTemplatesRoute: typeof AuthenticatedSettingsPromptTemplatesRoute
  AuthenticatedSettingsRunnerRoute: typeof AuthenticatedSettingsRunnerRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRunsRoute: AuthenticatedAiRunsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsMcpServersRoute:
    AuthenticatedSettingsMcpServersRouteWithChildren,
  AuthenticatedSettingsPromptTemplatesRoute:
    AuthenticatedSettingsPromptTemplatesRoute,
  AuthenticatedSettingsRunnerRoute: AuthenticatedSettingsRunnerRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
