/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAiRunsRouteImport } from './routes/_authenticated/ai-runs'
import { Route as AuthenticatedArtifactsRouteImport } from './routes/_authenticated/artifacts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedWorkflowRunsRouteImport } from './routes/_authenticated/workflow-runs'
import { Route as AuthenticatedWorkflowStepsRouteImport } from './routes/_authenticated/workflow-steps'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as SetupSupabaseRouteImport } from './routes/setup.supabase'
import { Route as AuthenticatedArtifactsCreateRouteImport } from './routes/_authenticated/artifacts/create'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedSettingsAccountsRouteImport } from './routes/_authenticated/settings/accounts'
import { Route as AuthenticatedSettingsAiProvidersRouteImport } from './routes/_authenticated/settings/ai-providers'
import { Route as AuthenticatedSettingsArtifactsRouteImport } from './routes/_authenticated/settings/artifacts'
import { Route as AuthenticatedSettingsGoogleDriveSetupRouteImport } from './routes/_authenticated/settings/google-drive-setup'
import { Route as AuthenticatedSettingsMcpServersRouteImport } from './routes/_authenticated/settings/mcp-servers'
import { Route as AuthenticatedSettingsPromptTemplatesRouteImport } from './routes/_authenticated/settings/prompt-templates'
import { Route as AuthenticatedSettingsRunnerRouteImport } from './routes/_authenticated/settings/runner'
import { Route as AuthenticatedSettingsSupabaseRouteImport } from './routes/_authenticated/settings/supabase'
import { Route as AuthenticatedWorkflowRunsRunIdRouteImport } from './routes/_authenticated/workflow-runs/$runId'
import { Route as AuthenticatedWorkflowStepsStepTypeRouteImport } from './routes/_authenticated/workflow-steps/$stepType'
import { Route as AuthenticatedWorkflowStepsCreateRouteImport } from './routes/_authenticated/workflow-steps/create'
import { Route as AuthenticatedWorkflowsWorkflowIdRouteImport } from './routes/_authenticated/workflows/$workflowId'
import { Route as AuthenticatedWorkflowsCreateRouteImport } from './routes/_authenticated/workflows/create'
import { Route as AuthenticatedProjectsProjectIdArtifactsRouteImport } from './routes/_authenticated/projects/$projectId/artifacts'
import { Route as AuthenticatedProjectsProjectIdBusinessLogicRouteImport } from './routes/_authenticated/projects/$projectId/business-logic'
import { Route as AuthenticatedProjectsProjectIdCodingPlanRouteImport } from './routes/_authenticated/projects/$projectId/coding-plan'
import { Route as AuthenticatedProjectsProjectIdDirectoryBindingsRouteImport } from './routes/_authenticated/projects/$projectId/directory-bindings'
import { Route as AuthenticatedProjectsProjectIdMasterScheduleRouteImport } from './routes/_authenticated/projects/$projectId/master-schedule'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects/$projectId/members'
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './routes/_authenticated/projects/$projectId/settings'
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated/projects/$projectId/tasks'
import { Route as AuthenticatedProjectsProjectIdTechSpecsRouteImport } from './routes/_authenticated/projects/$projectId/tech-specs'
import { Route as AuthenticatedProjectsProjectIdWorkflowsRouteImport } from './routes/_authenticated/projects/$projectId/workflows'
import { Route as AuthenticatedSettingsArtifactsCreateRouteImport } from './routes/_authenticated/settings/artifacts/create'
import { Route as AuthenticatedSettingsMcpServersCreateRouteImport } from './routes/_authenticated/settings/mcp-servers/create'
import { Route as AuthenticatedSettingsMcpServersInstancesRouteImport } from './routes/_authenticated/settings/mcp-servers/instances'
import { Route as AuthenticatedSettingsMcpServersJiraLinkRouteImport } from './routes/_authenticated/settings/mcp-servers/jira-link'
import { Route as AuthenticatedSettingsMcpServersMcpConnectTestRouteImport } from './routes/_authenticated/settings/mcp-servers/mcp-connect-test'
import { Route as AuthenticatedSettingsPromptTemplatesCreateRouteImport } from './routes/_authenticated/settings/prompt-templates/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiRunsRoute = AuthenticatedAiRunsRouteImport.update({
  id: '/ai-runs',
  path: '/ai-runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArtifactsRoute = AuthenticatedArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowRunsRoute =
  AuthenticatedWorkflowRunsRouteImport.update({
    id: '/workflow-runs',
    path: '/workflow-runs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowStepsRoute =
  AuthenticatedWorkflowStepsRouteImport.update({
    id: '/workflow-steps',
    path: '/workflow-steps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SetupSupabaseRoute = SetupSupabaseRouteImport.update({
  id: '/setup/supabase',
  path: '/setup/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArtifactsCreateRoute =
  AuthenticatedArtifactsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedArtifactsRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccountsRoute =
  AuthenticatedSettingsAccountsRouteImport.update({
    id: '/settings/accounts',
    path: '/settings/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAiProvidersRoute =
  AuthenticatedSettingsAiProvidersRouteImport.update({
    id: '/settings/ai-providers',
    path: '/settings/ai-providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsArtifactsRoute =
  AuthenticatedSettingsArtifactsRouteImport.update({
    id: '/settings/artifacts',
    path: '/settings/artifacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGoogleDriveSetupRoute =
  AuthenticatedSettingsGoogleDriveSetupRouteImport.update({
    id: '/settings/google-drive-setup',
    path: '/settings/google-drive-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMcpServersRoute =
  AuthenticatedSettingsMcpServersRouteImport.update({
    id: '/settings/mcp-servers',
    path: '/settings/mcp-servers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPromptTemplatesRoute =
  AuthenticatedSettingsPromptTemplatesRouteImport.update({
    id: '/settings/prompt-templates',
    path: '/settings/prompt-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRunnerRoute =
  AuthenticatedSettingsRunnerRouteImport.update({
    id: '/settings/runner',
    path: '/settings/runner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSupabaseRoute =
  AuthenticatedSettingsSupabaseRouteImport.update({
    id: '/settings/supabase',
    path: '/settings/supabase',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowRunsRunIdRoute =
  AuthenticatedWorkflowRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AuthenticatedWorkflowRunsRoute,
  } as any)
const AuthenticatedWorkflowStepsStepTypeRoute =
  AuthenticatedWorkflowStepsStepTypeRouteImport.update({
    id: '/$stepType',
    path: '/$stepType',
    getParentRoute: () => AuthenticatedWorkflowStepsRoute,
  } as any)
const AuthenticatedWorkflowStepsCreateRoute =
  AuthenticatedWorkflowStepsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedWorkflowStepsRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRoute =
  AuthenticatedWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedWorkflowsCreateRoute =
  AuthenticatedWorkflowsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedProjectsProjectIdArtifactsRoute =
  AuthenticatedProjectsProjectIdArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdBusinessLogicRoute =
  AuthenticatedProjectsProjectIdBusinessLogicRouteImport.update({
    id: '/business-logic',
    path: '/business-logic',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdCodingPlanRoute =
  AuthenticatedProjectsProjectIdCodingPlanRouteImport.update({
    id: '/coding-plan',
    path: '/coding-plan',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDirectoryBindingsRoute =
  AuthenticatedProjectsProjectIdDirectoryBindingsRouteImport.update({
    id: '/directory-bindings',
    path: '/directory-bindings',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMasterScheduleRoute =
  AuthenticatedProjectsProjectIdMasterScheduleRouteImport.update({
    id: '/master-schedule',
    path: '/master-schedule',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTechSpecsRoute =
  AuthenticatedProjectsProjectIdTechSpecsRouteImport.update({
    id: '/tech-specs',
    path: '/tech-specs',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdWorkflowsRoute =
  AuthenticatedProjectsProjectIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedSettingsArtifactsCreateRoute =
  AuthenticatedSettingsArtifactsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSettingsArtifactsRoute,
  } as any)
const AuthenticatedSettingsMcpServersCreateRoute =
  AuthenticatedSettingsMcpServersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSettingsMcpServersRoute,
  } as any)
const AuthenticatedSettingsMcpServersInstancesRoute =
  AuthenticatedSettingsMcpServersInstancesRouteImport.update({
    id: '/instances',
    path: '/instances',
    getParentRoute: () => AuthenticatedSettingsMcpServersRoute,
  } as any)
const AuthenticatedSettingsMcpServersJiraLinkRoute =
  AuthenticatedSettingsMcpServersJiraLinkRouteImport.update({
    id: '/jira-link',
    path: '/jira-link',
    getParentRoute: () => AuthenticatedSettingsMcpServersRoute,
  } as any)
const AuthenticatedSettingsMcpServersMcpConnectTestRoute =
  AuthenticatedSettingsMcpServersMcpConnectTestRouteImport.update({
    id: '/mcp-connect-test',
    path: '/mcp-connect-test',
    getParentRoute: () => AuthenticatedSettingsMcpServersRoute,
  } as any)
const AuthenticatedSettingsPromptTemplatesCreateRoute =
  AuthenticatedSettingsPromptTemplatesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSettingsPromptTemplatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/ai-runs': typeof AuthenticatedAiRunsRoute
  '/artifacts': typeof AuthenticatedArtifactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/workflow-runs': typeof AuthenticatedWorkflowRunsRouteWithChildren
  '/workflow-steps': typeof AuthenticatedWorkflowStepsRouteWithChildren
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/setup/supabase': typeof SetupSupabaseRoute
  '/artifacts/create': typeof AuthenticatedArtifactsCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/settings/accounts': typeof AuthenticatedSettingsAccountsRoute
  '/settings/ai-providers': typeof AuthenticatedSettingsAiProvidersRoute
  '/settings/artifacts': typeof AuthenticatedSettingsArtifactsRouteWithChildren
  '/settings/google-drive-setup': typeof AuthenticatedSettingsGoogleDriveSetupRoute
  '/settings/mcp-servers': typeof AuthenticatedSettingsMcpServersRouteWithChildren
  '/settings/prompt-templates': typeof AuthenticatedSettingsPromptTemplatesRouteWithChildren
  '/settings/runner': typeof AuthenticatedSettingsRunnerRoute
  '/settings/supabase': typeof AuthenticatedSettingsSupabaseRoute
  '/workflow-runs/$runId': typeof AuthenticatedWorkflowRunsRunIdRoute
  '/workflow-steps/$stepType': typeof AuthenticatedWorkflowStepsStepTypeRoute
  '/workflow-steps/create': typeof AuthenticatedWorkflowStepsCreateRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/workflows/create': typeof AuthenticatedWorkflowsCreateRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/artifacts': typeof AuthenticatedProjectsProjectIdArtifactsRoute
  '/projects/$projectId/business-logic': typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  '/projects/$projectId/coding-plan': typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  '/projects/$projectId/directory-bindings': typeof AuthenticatedProjectsProjectIdDirectoryBindingsRoute
  '/projects/$projectId/master-schedule': typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/tech-specs': typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  '/projects/$projectId/workflows': typeof AuthenticatedProjectsProjectIdWorkflowsRoute
  '/settings/artifacts/create': typeof AuthenticatedSettingsArtifactsCreateRoute
  '/settings/mcp-servers/create': typeof AuthenticatedSettingsMcpServersCreateRoute
  '/settings/mcp-servers/instances': typeof AuthenticatedSettingsMcpServersInstancesRoute
  '/settings/mcp-servers/jira-link': typeof AuthenticatedSettingsMcpServersJiraLinkRoute
  '/settings/mcp-servers/mcp-connect-test': typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
  '/settings/prompt-templates/create': typeof AuthenticatedSettingsPromptTemplatesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/ai-runs': typeof AuthenticatedAiRunsRoute
  '/artifacts': typeof AuthenticatedArtifactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/workflow-runs': typeof AuthenticatedWorkflowRunsRouteWithChildren
  '/workflow-steps': typeof AuthenticatedWorkflowStepsRouteWithChildren
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/setup/supabase': typeof SetupSupabaseRoute
  '/artifacts/create': typeof AuthenticatedArtifactsCreateRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/settings/accounts': typeof AuthenticatedSettingsAccountsRoute
  '/settings/ai-providers': typeof AuthenticatedSettingsAiProvidersRoute
  '/settings/artifacts': typeof AuthenticatedSettingsArtifactsRouteWithChildren
  '/settings/google-drive-setup': typeof AuthenticatedSettingsGoogleDriveSetupRoute
  '/settings/mcp-servers': typeof AuthenticatedSettingsMcpServersRouteWithChildren
  '/settings/prompt-templates': typeof AuthenticatedSettingsPromptTemplatesRouteWithChildren
  '/settings/runner': typeof AuthenticatedSettingsRunnerRoute
  '/settings/supabase': typeof AuthenticatedSettingsSupabaseRoute
  '/workflow-runs/$runId': typeof AuthenticatedWorkflowRunsRunIdRoute
  '/workflow-steps/$stepType': typeof AuthenticatedWorkflowStepsStepTypeRoute
  '/workflow-steps/create': typeof AuthenticatedWorkflowStepsCreateRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/workflows/create': typeof AuthenticatedWorkflowsCreateRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/artifacts': typeof AuthenticatedProjectsProjectIdArtifactsRoute
  '/projects/$projectId/business-logic': typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  '/projects/$projectId/coding-plan': typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  '/projects/$projectId/directory-bindings': typeof AuthenticatedProjectsProjectIdDirectoryBindingsRoute
  '/projects/$projectId/master-schedule': typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/tech-specs': typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  '/projects/$projectId/workflows': typeof AuthenticatedProjectsProjectIdWorkflowsRoute
  '/settings/artifacts/create': typeof AuthenticatedSettingsArtifactsCreateRoute
  '/settings/mcp-servers/create': typeof AuthenticatedSettingsMcpServersCreateRoute
  '/settings/mcp-servers/instances': typeof AuthenticatedSettingsMcpServersInstancesRoute
  '/settings/mcp-servers/jira-link': typeof AuthenticatedSettingsMcpServersJiraLinkRoute
  '/settings/mcp-servers/mcp-connect-test': typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
  '/settings/prompt-templates/create': typeof AuthenticatedSettingsPromptTemplatesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/_authenticated/ai-runs': typeof AuthenticatedAiRunsRoute
  '/_authenticated/artifacts': typeof AuthenticatedArtifactsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/workflow-runs': typeof AuthenticatedWorkflowRunsRouteWithChildren
  '/_authenticated/workflow-steps': typeof AuthenticatedWorkflowStepsRouteWithChildren
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/setup/supabase': typeof SetupSupabaseRoute
  '/_authenticated/artifacts/create': typeof AuthenticatedArtifactsCreateRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/settings/accounts': typeof AuthenticatedSettingsAccountsRoute
  '/_authenticated/settings/ai-providers': typeof AuthenticatedSettingsAiProvidersRoute
  '/_authenticated/settings/artifacts': typeof AuthenticatedSettingsArtifactsRouteWithChildren
  '/_authenticated/settings/google-drive-setup': typeof AuthenticatedSettingsGoogleDriveSetupRoute
  '/_authenticated/settings/mcp-servers': typeof AuthenticatedSettingsMcpServersRouteWithChildren
  '/_authenticated/settings/prompt-templates': typeof AuthenticatedSettingsPromptTemplatesRouteWithChildren
  '/_authenticated/settings/runner': typeof AuthenticatedSettingsRunnerRoute
  '/_authenticated/settings/supabase': typeof AuthenticatedSettingsSupabaseRoute
  '/_authenticated/workflow-runs/$runId': typeof AuthenticatedWorkflowRunsRunIdRoute
  '/_authenticated/workflow-steps/$stepType': typeof AuthenticatedWorkflowStepsStepTypeRoute
  '/_authenticated/workflow-steps/create': typeof AuthenticatedWorkflowStepsCreateRoute
  '/_authenticated/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/_authenticated/workflows/create': typeof AuthenticatedWorkflowsCreateRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/artifacts': typeof AuthenticatedProjectsProjectIdArtifactsRoute
  '/_authenticated/projects/$projectId/business-logic': typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  '/_authenticated/projects/$projectId/coding-plan': typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  '/_authenticated/projects/$projectId/directory-bindings': typeof AuthenticatedProjectsProjectIdDirectoryBindingsRoute
  '/_authenticated/projects/$projectId/master-schedule': typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/_authenticated/projects/$projectId/tech-specs': typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  '/_authenticated/projects/$projectId/workflows': typeof AuthenticatedProjectsProjectIdWorkflowsRoute
  '/_authenticated/settings/artifacts/create': typeof AuthenticatedSettingsArtifactsCreateRoute
  '/_authenticated/settings/mcp-servers/create': typeof AuthenticatedSettingsMcpServersCreateRoute
  '/_authenticated/settings/mcp-servers/instances': typeof AuthenticatedSettingsMcpServersInstancesRoute
  '/_authenticated/settings/mcp-servers/jira-link': typeof AuthenticatedSettingsMcpServersJiraLinkRoute
  '/_authenticated/settings/mcp-servers/mcp-connect-test': typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
  '/_authenticated/settings/prompt-templates/create': typeof AuthenticatedSettingsPromptTemplatesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/login'
    | '/ai-runs'
    | '/artifacts'
    | '/dashboard'
    | '/teams'
    | '/workflow-runs'
    | '/workflow-steps'
    | '/workflows'
    | '/setup/supabase'
    | '/artifacts/create'
    | '/projects/$projectId'
    | '/projects/create'
    | '/settings/accounts'
    | '/settings/ai-providers'
    | '/settings/artifacts'
    | '/settings/google-drive-setup'
    | '/settings/mcp-servers'
    | '/settings/prompt-templates'
    | '/settings/runner'
    | '/settings/supabase'
    | '/workflow-runs/$runId'
    | '/workflow-steps/$stepType'
    | '/workflow-steps/create'
    | '/workflows/$workflowId'
    | '/workflows/create'
    | '/projects/'
    | '/projects/$projectId/artifacts'
    | '/projects/$projectId/business-logic'
    | '/projects/$projectId/coding-plan'
    | '/projects/$projectId/directory-bindings'
    | '/projects/$projectId/master-schedule'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tech-specs'
    | '/projects/$projectId/workflows'
    | '/settings/artifacts/create'
    | '/settings/mcp-servers/create'
    | '/settings/mcp-servers/instances'
    | '/settings/mcp-servers/jira-link'
    | '/settings/mcp-servers/mcp-connect-test'
    | '/settings/prompt-templates/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/login'
    | '/ai-runs'
    | '/artifacts'
    | '/dashboard'
    | '/teams'
    | '/workflow-runs'
    | '/workflow-steps'
    | '/workflows'
    | '/setup/supabase'
    | '/artifacts/create'
    | '/projects/$projectId'
    | '/projects/create'
    | '/settings/accounts'
    | '/settings/ai-providers'
    | '/settings/artifacts'
    | '/settings/google-drive-setup'
    | '/settings/mcp-servers'
    | '/settings/prompt-templates'
    | '/settings/runner'
    | '/settings/supabase'
    | '/workflow-runs/$runId'
    | '/workflow-steps/$stepType'
    | '/workflow-steps/create'
    | '/workflows/$workflowId'
    | '/workflows/create'
    | '/projects'
    | '/projects/$projectId/artifacts'
    | '/projects/$projectId/business-logic'
    | '/projects/$projectId/coding-plan'
    | '/projects/$projectId/directory-bindings'
    | '/projects/$projectId/master-schedule'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tech-specs'
    | '/projects/$projectId/workflows'
    | '/settings/artifacts/create'
    | '/settings/mcp-servers/create'
    | '/settings/mcp-servers/instances'
    | '/settings/mcp-servers/jira-link'
    | '/settings/mcp-servers/mcp-connect-test'
    | '/settings/prompt-templates/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/guide'
    | '/login'
    | '/_authenticated/ai-runs'
    | '/_authenticated/artifacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/teams'
    | '/_authenticated/workflow-runs'
    | '/_authenticated/workflow-steps'
    | '/_authenticated/workflows'
    | '/setup/supabase'
    | '/_authenticated/artifacts/create'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/create'
    | '/_authenticated/settings/accounts'
    | '/_authenticated/settings/ai-providers'
    | '/_authenticated/settings/artifacts'
    | '/_authenticated/settings/google-drive-setup'
    | '/_authenticated/settings/mcp-servers'
    | '/_authenticated/settings/prompt-templates'
    | '/_authenticated/settings/runner'
    | '/_authenticated/settings/supabase'
    | '/_authenticated/workflow-runs/$runId'
    | '/_authenticated/workflow-steps/$stepType'
    | '/_authenticated/workflow-steps/create'
    | '/_authenticated/workflows/$workflowId'
    | '/_authenticated/workflows/create'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/artifacts'
    | '/_authenticated/projects/$projectId/business-logic'
    | '/_authenticated/projects/$projectId/coding-plan'
    | '/_authenticated/projects/$projectId/directory-bindings'
    | '/_authenticated/projects/$projectId/master-schedule'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/projects/$projectId/tech-specs'
    | '/_authenticated/projects/$projectId/workflows'
    | '/_authenticated/settings/artifacts/create'
    | '/_authenticated/settings/mcp-servers/create'
    | '/_authenticated/settings/mcp-servers/instances'
    | '/_authenticated/settings/mcp-servers/jira-link'
    | '/_authenticated/settings/mcp-servers/mcp-connect-test'
    | '/_authenticated/settings/prompt-templates/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  SetupSupabaseRoute: typeof SetupSupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-runs': {
      id: '/_authenticated/ai-runs'
      path: '/ai-runs'
      fullPath: '/ai-runs'
      preLoaderRoute: typeof AuthenticatedAiRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artifacts': {
      id: '/_authenticated/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AuthenticatedArtifactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow-runs': {
      id: '/_authenticated/workflow-runs'
      path: '/workflow-runs'
      fullPath: '/workflow-runs'
      preLoaderRoute: typeof AuthenticatedWorkflowRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow-steps': {
      id: '/_authenticated/workflow-steps'
      path: '/workflow-steps'
      fullPath: '/workflow-steps'
      preLoaderRoute: typeof AuthenticatedWorkflowStepsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/setup/supabase': {
      id: '/setup/supabase'
      path: '/setup/supabase'
      fullPath: '/setup/supabase'
      preLoaderRoute: typeof SetupSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/artifacts/create': {
      id: '/_authenticated/artifacts/create'
      path: '/create'
      fullPath: '/artifacts/create'
      preLoaderRoute: typeof AuthenticatedArtifactsCreateRouteImport
      parentRoute: typeof AuthenticatedArtifactsRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/accounts': {
      id: '/_authenticated/settings/accounts'
      path: '/settings/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthenticatedSettingsAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/ai-providers': {
      id: '/_authenticated/settings/ai-providers'
      path: '/settings/ai-providers'
      fullPath: '/settings/ai-providers'
      preLoaderRoute: typeof AuthenticatedSettingsAiProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/artifacts': {
      id: '/_authenticated/settings/artifacts'
      path: '/settings/artifacts'
      fullPath: '/settings/artifacts'
      preLoaderRoute: typeof AuthenticatedSettingsArtifactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/google-drive-setup': {
      id: '/_authenticated/settings/google-drive-setup'
      path: '/settings/google-drive-setup'
      fullPath: '/settings/google-drive-setup'
      preLoaderRoute: typeof AuthenticatedSettingsGoogleDriveSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mcp-servers': {
      id: '/_authenticated/settings/mcp-servers'
      path: '/settings/mcp-servers'
      fullPath: '/settings/mcp-servers'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/prompt-templates': {
      id: '/_authenticated/settings/prompt-templates'
      path: '/settings/prompt-templates'
      fullPath: '/settings/prompt-templates'
      preLoaderRoute: typeof AuthenticatedSettingsPromptTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/runner': {
      id: '/_authenticated/settings/runner'
      path: '/settings/runner'
      fullPath: '/settings/runner'
      preLoaderRoute: typeof AuthenticatedSettingsRunnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/supabase': {
      id: '/_authenticated/settings/supabase'
      path: '/settings/supabase'
      fullPath: '/settings/supabase'
      preLoaderRoute: typeof AuthenticatedSettingsSupabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow-runs/$runId': {
      id: '/_authenticated/workflow-runs/$runId'
      path: '/$runId'
      fullPath: '/workflow-runs/$runId'
      preLoaderRoute: typeof AuthenticatedWorkflowRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowRunsRoute
    }
    '/_authenticated/workflow-steps/$stepType': {
      id: '/_authenticated/workflow-steps/$stepType'
      path: '/$stepType'
      fullPath: '/workflow-steps/$stepType'
      preLoaderRoute: typeof AuthenticatedWorkflowStepsStepTypeRouteImport
      parentRoute: typeof AuthenticatedWorkflowStepsRoute
    }
    '/_authenticated/workflow-steps/create': {
      id: '/_authenticated/workflow-steps/create'
      path: '/create'
      fullPath: '/workflow-steps/create'
      preLoaderRoute: typeof AuthenticatedWorkflowStepsCreateRouteImport
      parentRoute: typeof AuthenticatedWorkflowStepsRoute
    }
    '/_authenticated/workflows/$workflowId': {
      id: '/_authenticated/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/workflows/create': {
      id: '/_authenticated/workflows/create'
      path: '/create'
      fullPath: '/workflows/create'
      preLoaderRoute: typeof AuthenticatedWorkflowsCreateRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/projects/$projectId/artifacts': {
      id: '/_authenticated/projects/$projectId/artifacts'
      path: '/artifacts'
      fullPath: '/projects/$projectId/artifacts'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdArtifactsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/business-logic': {
      id: '/_authenticated/projects/$projectId/business-logic'
      path: '/business-logic'
      fullPath: '/projects/$projectId/business-logic'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBusinessLogicRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/coding-plan': {
      id: '/_authenticated/projects/$projectId/coding-plan'
      path: '/coding-plan'
      fullPath: '/projects/$projectId/coding-plan'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdCodingPlanRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/directory-bindings': {
      id: '/_authenticated/projects/$projectId/directory-bindings'
      path: '/directory-bindings'
      fullPath: '/projects/$projectId/directory-bindings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDirectoryBindingsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/master-schedule': {
      id: '/_authenticated/projects/$projectId/master-schedule'
      path: '/master-schedule'
      fullPath: '/projects/$projectId/master-schedule'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMasterScheduleRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tech-specs': {
      id: '/_authenticated/projects/$projectId/tech-specs'
      path: '/tech-specs'
      fullPath: '/projects/$projectId/tech-specs'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTechSpecsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/workflows': {
      id: '/_authenticated/projects/$projectId/workflows'
      path: '/workflows'
      fullPath: '/projects/$projectId/workflows'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWorkflowsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/settings/artifacts/create': {
      id: '/_authenticated/settings/artifacts/create'
      path: '/create'
      fullPath: '/settings/artifacts/create'
      preLoaderRoute: typeof AuthenticatedSettingsArtifactsCreateRouteImport
      parentRoute: typeof AuthenticatedSettingsArtifactsRoute
    }
    '/_authenticated/settings/mcp-servers/create': {
      id: '/_authenticated/settings/mcp-servers/create'
      path: '/create'
      fullPath: '/settings/mcp-servers/create'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersCreateRouteImport
      parentRoute: typeof AuthenticatedSettingsMcpServersRoute
    }
    '/_authenticated/settings/mcp-servers/instances': {
      id: '/_authenticated/settings/mcp-servers/instances'
      path: '/instances'
      fullPath: '/settings/mcp-servers/instances'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersInstancesRouteImport
      parentRoute: typeof AuthenticatedSettingsMcpServersRoute
    }
    '/_authenticated/settings/mcp-servers/jira-link': {
      id: '/_authenticated/settings/mcp-servers/jira-link'
      path: '/jira-link'
      fullPath: '/settings/mcp-servers/jira-link'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersJiraLinkRouteImport
      parentRoute: typeof AuthenticatedSettingsMcpServersRoute
    }
    '/_authenticated/settings/mcp-servers/mcp-connect-test': {
      id: '/_authenticated/settings/mcp-servers/mcp-connect-test'
      path: '/mcp-connect-test'
      fullPath: '/settings/mcp-servers/mcp-connect-test'
      preLoaderRoute: typeof AuthenticatedSettingsMcpServersMcpConnectTestRouteImport
      parentRoute: typeof AuthenticatedSettingsMcpServersRoute
    }
    '/_authenticated/settings/prompt-templates/create': {
      id: '/_authenticated/settings/prompt-templates/create'
      path: '/create'
      fullPath: '/settings/prompt-templates/create'
      preLoaderRoute: typeof AuthenticatedSettingsPromptTemplatesCreateRouteImport
      parentRoute: typeof AuthenticatedSettingsPromptTemplatesRoute
    }
  }
}

interface AuthenticatedArtifactsRouteChildren {
  AuthenticatedArtifactsCreateRoute: typeof AuthenticatedArtifactsCreateRoute
}

const AuthenticatedArtifactsRouteChildren: AuthenticatedArtifactsRouteChildren =
  {
    AuthenticatedArtifactsCreateRoute: AuthenticatedArtifactsCreateRoute,
  }

const AuthenticatedArtifactsRouteWithChildren =
  AuthenticatedArtifactsRoute._addFileChildren(
    AuthenticatedArtifactsRouteChildren,
  )

interface AuthenticatedWorkflowRunsRouteChildren {
  AuthenticatedWorkflowRunsRunIdRoute: typeof AuthenticatedWorkflowRunsRunIdRoute
}

const AuthenticatedWorkflowRunsRouteChildren: AuthenticatedWorkflowRunsRouteChildren =
  {
    AuthenticatedWorkflowRunsRunIdRoute: AuthenticatedWorkflowRunsRunIdRoute,
  }

const AuthenticatedWorkflowRunsRouteWithChildren =
  AuthenticatedWorkflowRunsRoute._addFileChildren(
    AuthenticatedWorkflowRunsRouteChildren,
  )

interface AuthenticatedWorkflowStepsRouteChildren {
  AuthenticatedWorkflowStepsStepTypeRoute: typeof AuthenticatedWorkflowStepsStepTypeRoute
  AuthenticatedWorkflowStepsCreateRoute: typeof AuthenticatedWorkflowStepsCreateRoute
}

const AuthenticatedWorkflowStepsRouteChildren: AuthenticatedWorkflowStepsRouteChildren =
  {
    AuthenticatedWorkflowStepsStepTypeRoute:
      AuthenticatedWorkflowStepsStepTypeRoute,
    AuthenticatedWorkflowStepsCreateRoute:
      AuthenticatedWorkflowStepsCreateRoute,
  }

const AuthenticatedWorkflowStepsRouteWithChildren =
  AuthenticatedWorkflowStepsRoute._addFileChildren(
    AuthenticatedWorkflowStepsRouteChildren,
  )

interface AuthenticatedWorkflowsRouteChildren {
  AuthenticatedWorkflowsWorkflowIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRoute
  AuthenticatedWorkflowsCreateRoute: typeof AuthenticatedWorkflowsCreateRoute
}

const AuthenticatedWorkflowsRouteChildren: AuthenticatedWorkflowsRouteChildren =
  {
    AuthenticatedWorkflowsWorkflowIdRoute:
      AuthenticatedWorkflowsWorkflowIdRoute,
    AuthenticatedWorkflowsCreateRoute: AuthenticatedWorkflowsCreateRoute,
  }

const AuthenticatedWorkflowsRouteWithChildren =
  AuthenticatedWorkflowsRoute._addFileChildren(
    AuthenticatedWorkflowsRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdArtifactsRoute: typeof AuthenticatedProjectsProjectIdArtifactsRoute
  AuthenticatedProjectsProjectIdBusinessLogicRoute: typeof AuthenticatedProjectsProjectIdBusinessLogicRoute
  AuthenticatedProjectsProjectIdCodingPlanRoute: typeof AuthenticatedProjectsProjectIdCodingPlanRoute
  AuthenticatedProjectsProjectIdDirectoryBindingsRoute: typeof AuthenticatedProjectsProjectIdDirectoryBindingsRoute
  AuthenticatedProjectsProjectIdMasterScheduleRoute: typeof AuthenticatedProjectsProjectIdMasterScheduleRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRoute
  AuthenticatedProjectsProjectIdTechSpecsRoute: typeof AuthenticatedProjectsProjectIdTechSpecsRoute
  AuthenticatedProjectsProjectIdWorkflowsRoute: typeof AuthenticatedProjectsProjectIdWorkflowsRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdArtifactsRoute:
      AuthenticatedProjectsProjectIdArtifactsRoute,
    AuthenticatedProjectsProjectIdBusinessLogicRoute:
      AuthenticatedProjectsProjectIdBusinessLogicRoute,
    AuthenticatedProjectsProjectIdCodingPlanRoute:
      AuthenticatedProjectsProjectIdCodingPlanRoute,
    AuthenticatedProjectsProjectIdDirectoryBindingsRoute:
      AuthenticatedProjectsProjectIdDirectoryBindingsRoute,
    AuthenticatedProjectsProjectIdMasterScheduleRoute:
      AuthenticatedProjectsProjectIdMasterScheduleRoute,
    AuthenticatedProjectsProjectIdMembersRoute:
      AuthenticatedProjectsProjectIdMembersRoute,
    AuthenticatedProjectsProjectIdSettingsRoute:
      AuthenticatedProjectsProjectIdSettingsRoute,
    AuthenticatedProjectsProjectIdTasksRoute:
      AuthenticatedProjectsProjectIdTasksRoute,
    AuthenticatedProjectsProjectIdTechSpecsRoute:
      AuthenticatedProjectsProjectIdTechSpecsRoute,
    AuthenticatedProjectsProjectIdWorkflowsRoute:
      AuthenticatedProjectsProjectIdWorkflowsRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedSettingsArtifactsRouteChildren {
  AuthenticatedSettingsArtifactsCreateRoute: typeof AuthenticatedSettingsArtifactsCreateRoute
}

const AuthenticatedSettingsArtifactsRouteChildren: AuthenticatedSettingsArtifactsRouteChildren =
  {
    AuthenticatedSettingsArtifactsCreateRoute:
      AuthenticatedSettingsArtifactsCreateRoute,
  }

const AuthenticatedSettingsArtifactsRouteWithChildren =
  AuthenticatedSettingsArtifactsRoute._addFileChildren(
    AuthenticatedSettingsArtifactsRouteChildren,
  )

interface AuthenticatedSettingsMcpServersRouteChildren {
  AuthenticatedSettingsMcpServersCreateRoute: typeof AuthenticatedSettingsMcpServersCreateRoute
  AuthenticatedSettingsMcpServersInstancesRoute: typeof AuthenticatedSettingsMcpServersInstancesRoute
  AuthenticatedSettingsMcpServersJiraLinkRoute: typeof AuthenticatedSettingsMcpServersJiraLinkRoute
  AuthenticatedSettingsMcpServersMcpConnectTestRoute: typeof AuthenticatedSettingsMcpServersMcpConnectTestRoute
}

const AuthenticatedSettingsMcpServersRouteChildren: AuthenticatedSettingsMcpServersRouteChildren =
  {
    AuthenticatedSettingsMcpServersCreateRoute:
      AuthenticatedSettingsMcpServersCreateRoute,
    AuthenticatedSettingsMcpServersInstancesRoute:
      AuthenticatedSettingsMcpServersInstancesRoute,
    AuthenticatedSettingsMcpServersJiraLinkRoute:
      AuthenticatedSettingsMcpServersJiraLinkRoute,
    AuthenticatedSettingsMcpServersMcpConnectTestRoute:
      AuthenticatedSettingsMcpServersMcpConnectTestRoute,
  }

const AuthenticatedSettingsMcpServersRouteWithChildren =
  AuthenticatedSettingsMcpServersRoute._addFileChildren(
    AuthenticatedSettingsMcpServersRouteChildren,
  )

interface AuthenticatedSettingsPromptTemplatesRouteChildren {
  AuthenticatedSettingsPromptTemplatesCreateRoute: typeof AuthenticatedSettingsPromptTemplatesCreateRoute
}

const AuthenticatedSettingsPromptTemplatesRouteChildren: AuthenticatedSettingsPromptTemplatesRouteChildren =
  {
    AuthenticatedSettingsPromptTemplatesCreateRoute:
      AuthenticatedSettingsPromptTemplatesCreateRoute,
  }

const AuthenticatedSettingsPromptTemplatesRouteWithChildren =
  AuthenticatedSettingsPromptTemplatesRoute._addFileChildren(
    AuthenticatedSettingsPromptTemplatesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiRunsRoute: typeof AuthenticatedAiRunsRoute
  AuthenticatedArtifactsRoute: typeof AuthenticatedArtifactsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedWorkflowRunsRoute: typeof AuthenticatedWorkflowRunsRouteWithChildren
  AuthenticatedWorkflowStepsRoute: typeof AuthenticatedWorkflowStepsRouteWithChildren
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRouteWithChildren
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedSettingsAccountsRoute: typeof AuthenticatedSettingsAccountsRoute
  AuthenticatedSettingsAiProvidersRoute: typeof AuthenticatedSettingsAiProvidersRoute
  AuthenticatedSettingsArtifactsRoute: typeof AuthenticatedSettingsArtifactsRouteWithChildren
  AuthenticatedSettingsGoogleDriveSetupRoute: typeof AuthenticatedSettingsGoogleDriveSetupRoute
  AuthenticatedSettingsMcpServersRoute: typeof AuthenticatedSettingsMcpServersRouteWithChildren
  AuthenticatedSettingsPromptTemplatesRoute: typeof AuthenticatedSettingsPromptTemplatesRouteWithChildren
  AuthenticatedSettingsRunnerRoute: typeof AuthenticatedSettingsRunnerRoute
  AuthenticatedSettingsSupabaseRoute: typeof AuthenticatedSettingsSupabaseRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRunsRoute: AuthenticatedAiRunsRoute,
  AuthenticatedArtifactsRoute: AuthenticatedArtifactsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedWorkflowRunsRoute: AuthenticatedWorkflowRunsRouteWithChildren,
  AuthenticatedWorkflowStepsRoute: AuthenticatedWorkflowStepsRouteWithChildren,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRouteWithChildren,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedSettingsAccountsRoute: AuthenticatedSettingsAccountsRoute,
  AuthenticatedSettingsAiProvidersRoute: AuthenticatedSettingsAiProvidersRoute,
  AuthenticatedSettingsArtifactsRoute:
    AuthenticatedSettingsArtifactsRouteWithChildren,
  AuthenticatedSettingsGoogleDriveSetupRoute:
    AuthenticatedSettingsGoogleDriveSetupRoute,
  AuthenticatedSettingsMcpServersRoute:
    AuthenticatedSettingsMcpServersRouteWithChildren,
  AuthenticatedSettingsPromptTemplatesRoute:
    AuthenticatedSettingsPromptTemplatesRouteWithChildren,
  AuthenticatedSettingsRunnerRoute: AuthenticatedSettingsRunnerRoute,
  AuthenticatedSettingsSupabaseRoute: AuthenticatedSettingsSupabaseRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  SetupSupabaseRoute: SetupSupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
