import { createFileRoute } from "@tanstack/react-router";
import { useMemo } from "react";

import { PageFrame } from "@/components/common/page-frame";
import { ProjectSectionNav } from "@/components/project/project-section-nav";
import { createGatewayBundle } from "@/data/repository/browser-factory";
import type { ArtifactRun } from "@/domain/model/entity/workflow-engine";
import { ListArtifactRunsUseCase } from "@/domain/usecase/workflow-engine/list-artifact-runs-usecase";
import { Badge } from "@/presentation/components/ui/badge";

type ProjectArtifactsLoaderGateways = {
  projectGateway: {
    getProjectById: (projectId: string) => Promise<unknown>;
  };
  workflowEngineGateway: ConstructorParameters<typeof ListArtifactRunsUseCase>[0];
};

export async function loadProjectArtifactsData(
  gateways: ProjectArtifactsLoaderGateways,
  projectId: string
) {
  const [project, artifactRuns] = await Promise.all([
    gateways.projectGateway.getProjectById(projectId),
    new ListArtifactRunsUseCase(gateways.workflowEngineGateway).execute(projectId),
  ]);

  return {
    project,
    artifactRuns,
    projectId,
  };
}

export const Route = createFileRoute("/_authenticated/projects/$projectId/artifacts")({
  loader: async ({ params }) => {
    const gateways = await createGatewayBundle();
    return loadProjectArtifactsData(gateways, params.projectId);
  },
  component: ProjectArtifactsPage,
});

function ProjectArtifactsPage() {
  const { project, artifactRuns, projectId } = Route.useLoaderData();

  if (!project) {
    return null;
  }

  return (
    <ProjectArtifactsContent artifactRuns={artifactRuns} key={project.id} projectId={projectId} />
  );
}

function ProjectArtifactsContent({
  artifactRuns,
  projectId,
}: {
  artifactRuns: ArtifactRun[];
  projectId: string;
}) {
  const groupedRuns = useMemo(() => {
    const groups = new Map<string, ArtifactRun[]>();
    for (const artifact of artifactRuns) {
      const bucket = groups.get(artifact.workflowRunId) ?? [];
      bucket.push(artifact);
      groups.set(artifact.workflowRunId, bucket);
    }
    return Array.from(groups.entries()).sort((a, b) => {
      const aTime = a[1][0]?.createdAt ?? "";
      const bTime = b[1][0]?.createdAt ?? "";
      return bTime.localeCompare(aTime);
    });
  }, [artifactRuns]);

  return (
    <PageFrame
      description="Artifacts generated by workflow runs in this project."
      title="Project Artifacts"
    >
      <div className="space-y-6">
        <ProjectSectionNav projectId={projectId} />

        <section className="rounded-[1.6rem] border border-border bg-background/70 p-6">
          <p className="font-mono text-xs uppercase tracking-[0.28em] text-muted-foreground">
            Workflow Runs
          </p>
          <h2 className="mt-3 text-2xl font-semibold tracking-tight">
            Grouped artifact runs
          </h2>
          <p className="mt-2 text-sm text-muted-foreground">
            Each run below contains one or more generated artifact records keyed by artifact
            definition.
          </p>

          <div className="mt-6 space-y-4">
            {groupedRuns.length === 0 ? (
              <p className="text-sm text-muted-foreground">No artifact runs recorded yet.</p>
            ) : (
              groupedRuns.map(([workflowRunId, runs]) => (
                <div key={workflowRunId} className="rounded-2xl border border-border bg-card p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="font-semibold">{workflowRunId}</p>
                      <p className="mt-1 text-xs text-muted-foreground">
                        {runs.length} artifact{runs.length === 1 ? "" : "s"}
                      </p>
                    </div>
                    <Badge tone={runs.some((item) => item.syncStatus === "synced") ? "success" : "warning"}>
                      {runs.some((item) => item.syncStatus === "synced") ? "synced" : "local"}
                    </Badge>
                  </div>

                  <div className="mt-4 space-y-3">
                    {runs.map((artifact) => (
                      <div
                        key={artifact.id}
                        className="rounded-2xl border border-border bg-background/70 p-4"
                      >
                        <div className="flex flex-wrap items-center justify-between gap-3">
                          <div>
                            <p className="font-medium">{artifact.title}</p>
                            <p className="text-xs text-muted-foreground">
                              {artifact.artifactDefinitionKey} / {artifact.workflowRunStepId ?? "no step"}
                            </p>
                          </div>
                          <Badge tone={artifact.syncStatus === "synced" ? "success" : "neutral"}>
                            {artifact.syncStatus}
                          </Badge>
                        </div>
                        <div className="mt-3 grid gap-2 text-sm text-muted-foreground md:grid-cols-2">
                          <p>Local: {artifact.localPath}</p>
                          <p>Remote: {artifact.remotePath || "Not synced"}</p>
                          <p>Remote URL: {artifact.remoteUrl || "Not synced"}</p>
                          <p>Updated: {new Date(artifact.updatedAt).toLocaleString()}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))
            )}
          </div>
        </section>
      </div>
    </PageFrame>
  );
}
